In [1]:
from sklearn.linear_model import LogisticRegression 
def data_loader(df):
    import numpy as np # importing Numpy; Python library 
    import pandas as pd # Importing Pandas to 
    # reading csv file
    df = pd.read_csv("creditcard.csv") 
    # drop Time Column from the dataset
    df.drop('Time', inplace=True, axis=1)
    #return data(csv) file
    return df


In [55]:
data = data_loader("creditcard.csv")
data.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.098698  0.363787  0.090794  ... -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  0.207643  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024 -0.054952  ... -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  0.753074  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 30 columns]

In [9]:
def pre_processing(df):
    for column in df.columns:
        df[column] = df[column]  / df[column].abs().max()       
    return df
data = pre_processing(data)
data.head(5)

V1        V2        V3        V4        V5        V6        V7  \
0 -0.024107 -0.001001  0.052485  0.081667 -0.002974  0.006308  0.001987   
1  0.021129  0.003660  0.003445  0.026557  0.000528 -0.001124 -0.000653   
2 -0.024081 -0.018430  0.036693  0.022505 -0.004424  0.024563  0.006563   
3 -0.017130 -0.002547  0.037102 -0.051157 -0.000091  0.017015  0.001970   
4 -0.020533  0.012071  0.032048  0.023883 -0.003580  0.001309  0.004917   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.001348  0.023327  0.003693  ... -0.000526  0.025412 -0.002466  0.014599   
1  0.001162 -0.016379 -0.006791  ... -0.006482 -0.058416  0.002261 -0.074129   
2  0.003383 -0.097124  0.008445  ...  0.007120  0.070582  0.020296 -0.150349   
3  0.005155 -0.088940 -0.002235  ... -0.003109  0.000482 -0.004247 -0.256421   
4 -0.003695  0.052436  0.030627  ... -0.000271  0.073015 -0.003068  0.030814   

        V25       V26       V27       V28    Amount  Class  
0  0.012485 -0.053766  0.004225 -0.000622  0.005824    0.0  
1  0.016237  0.035792 -0.000284  0.000435  0.000105    0.0  
2 -0.031824 -0.039546 -0.001751 -0.001765  0.014739    0.0  
3  0.062880 -0.063096  0.001984  0.001816  0.004807    0.0  
4 -0.020010  0.142804  0.006941  0.006356  0.002724    0.0  

[5 rows x 30 columns]

In [56]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, shuffle = True, random_state = 8)
# Use the same function above for the validation set
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state= 8) # 0.25 x 0.8 = 0.2
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))
print("X_val shape: {}".format(X_val.shape))
print("y val shape: {}".format(y_val.shape))

X_train shape: (170883, 29)
y_train shape: (170883,)
X_test shape: (56962, 29)
y_test shape: (56962,)
X_val shape: (56962, 29)
y val shape: (56962,)


In [52]:
model = LogisticRegression(penalty = "l2")
model.fit(X_train, y_train)
predictions = model.predict(X_test)
#predictions = model.predict(X_val)
print(predictions )
score = model.score(X_val, y_val)
print(score)
from sklearn.metrics import f1_score
f1= f1_score(X_test, predictions)
print(f1)

[0. 0. 0. ... 0. 0. 0.]
0.9990168884519505


ValueError: Classification metrics can't handle a mix of continuous-multioutput and binary targets

In [25]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
cm = metrics.confusion_matrix(y_val, predictions)
print(cm)

[[56846     9]
 [   47    60]]


In [30]:
co = model.coef_
co.shape

(1, 29)

In [67]:

import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import numpy as np 
from numpy import log,dot,exp,shape
import matplotlib.pyplot as plt
# filter warnings
warnings.filterwarnings('ignore')

In [68]:
def data_loader(df):
    import numpy as np # importing Numpy; Python library 
    import pandas as pd # Importing Pandas to 
    # reading csv file
    df = pd.read_csv("creditcard.csv") 
    # drop Time Column from the dataset
    df.drop('Time', inplace=True, axis=1)
    #return data(csv) file
    return df

In [59]:
data = data_loader("creditcard.csv")
data.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.098698  0.363787  0.090794  ... -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  0.207643  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024 -0.054952  ... -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  0.753074  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 30 columns]

In [34]:
def pre_processing(df):
    for column in df.columns:
        df[column] = df[column]  / df[column].abs().max()       
    return df
data = pre_processing(data)
data.head(5)

V1        V2        V3        V4        V5        V6        V7  \
0 -0.024107 -0.001001  0.052485  0.081667 -0.002974  0.006308  0.001987   
1  0.021129  0.003660  0.003445  0.026557  0.000528 -0.001124 -0.000653   
2 -0.024081 -0.018430  0.036693  0.022505 -0.004424  0.024563  0.006563   
3 -0.017130 -0.002547  0.037102 -0.051157 -0.000091  0.017015  0.001970   
4 -0.020533  0.012071  0.032048  0.023883 -0.003580  0.001309  0.004917   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.001348  0.023327  0.003693  ... -0.000526  0.025412 -0.002466  0.014599   
1  0.001162 -0.016379 -0.006791  ... -0.006482 -0.058416  0.002261 -0.074129   
2  0.003383 -0.097124  0.008445  ...  0.007120  0.070582  0.020296 -0.150349   
3  0.005155 -0.088940 -0.002235  ... -0.003109  0.000482 -0.004247 -0.256421   
4 -0.003695  0.052436  0.030627  ... -0.000271  0.073015 -0.003068  0.030814   

        V25       V26       V27       V28    Amount  Class  
0  0.012485 -0.053766  0.004225 -0.000622  0.005824    0.0  
1  0.016237  0.035792 -0.000284  0.000435  0.000105    0.0  
2 -0.031824 -0.039546 -0.001751 -0.001765  0.014739    0.0  
3  0.062880 -0.063096  0.001984  0.001816  0.004807    0.0  
4 -0.020010  0.142804  0.006941  0.006356  0.002724    0.0  

[5 rows x 30 columns]

(284807, 29)

In [69]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, shuffle = True, random_state = 8)
# Use the same function above for the validation set
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state= 8) # 0.25 x 0.8 = 0.2
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))
print("X_val shape: {}".format(X_val.shape))
print("y val shape: {}".format(y_val.shape))

X_train shape: (170883, 29)
y_train shape: (170883,)
X_test shape: (56962, 29)
y_test shape: (56962,)
X_val shape: (56962, 29)
y val shape: (56962,)


In [70]:
def initialize(self,X):
    weights = np.zeros((shape(X)[1]+1,1))
    #print(weights)
    X = np.c_[np.ones((shape(X)[0],1)),X]
    #print(X)
    return weights,X


In [71]:
def sigmoid(z):
    """
    return the sigmoid of z
    """
    
    return 1/ (1 + np.exp(-z))

In [73]:
weights,X = initialize(X,X)

In [39]:
def costFunctionReg(weights, X_train, Y_train ,Lambda):
    """
    Take in numpy array of theta, X, and y to return the regularize cost function and gradient
    of a logistic regression
    """
    
    m=len(y_train)
    print(m)
    y = y_train[:,np.newaxis]
    #y = y_train
    #print(y)
    predictions = sigmoid(X @ weights)
    error = (-y * np.log(predictions)) - ((1-y)*np.log(1-predictions))
    cost = 1/m * sum(error)
    regCost= cost + Lambda/(2*m) * sum(weights**2)
    
    # compute gradient
    j_0= 1/m * (X.transpose() @ (predictions - y))[0]
    j_1 = 1/m * (X.transpose() @ (predictions - y))[1:] + (Lambda/m)* weights[1:]
    grad= np.vstack((j_0[:,np.newaxis],j_1))
    return cost[0], grad

In [40]:
Lambda = 0.01
cost, grad = costFunctionReg(weights, X, y_train, Lambda)
print(cost)

170883
0.6931471805585467


In [42]:
def costFunctionReg(theta, X, y ,Lambda):
    """
    Take in numpy array of theta, X, and y to return the regularize cost function and gradient
    of a logistic regression
    """
    
    m=len(y)
    y=y[:,np.newaxis]
    predictions = sigmoid(X @ theta)
    error = (-y * np.log(predictions)) - ((1-y)*np.log(1-predictions))
    cost = 1/m * sum(error)
    regCost= cost + Lambda/(2*m) * sum(theta**2)
    
    # compute gradient
    j_0= 1/m * (X.transpose() @ (predictions - y))[0]
    j_1 = 1/m * (X.transpose() @ (predictions - y))[1:] + (Lambda/m)* theta[1:]
    grad= np.vstack((j_0[:,np.newaxis],j_1))
    return cost[0], grad

In [74]:
def F1_score(y,y_hat):
    tp,tn,fp,fn = 0,0,0,0
    for i in range(len(y)):
        if y[i] == 1 and y_hat[i] == 1:
            tp += 1
        elif y[i] == 1 and y_hat[i] == 0:
            fn += 1
        elif y[i] == 0 and y_hat[i] == 1:
            fp += 1
        elif y[i] == 0 and y_hat[i] == 0:
            tn += 1

    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    f1_score = 2*precision*recall/(precision+recall)
    return f1_score

In [75]:
class LogidticRegression(object):
    def sigmoid(self,z):
        sig = 1/(1+exp(-z))
        return sig
    def initialize(self,X):
        weights = np.zeros((shape(X)[1]+1,1))
        X = np.c_[np.ones((shape(X)[0],1)),X]
        return weights,X
    def fit(self,X,y,alpha=0.001,iter=400):
        weights,X = self.initialize(X)
        def cost(theta):
            z = dot(X,theta)
            cost0 = y.T.dot(log(self.sigmoid(z)))
            cost1 = (1-y).T.dot(log(1-self.sigmoid(z)))
            cost = -((cost1 + cost0))/len(y)
            return cost
        cost_list = np.zeros(iter,)
        for i in range(iter):
            weights = weights - alpha*dot(X.T,self.sigmoid(dot(X,weights))-np.reshape(y,(len(y),1)))
            cost_list[i] = cost(weights)
        self.weights = weights
        return cost_list
    def predict(self,X):
        z = dot(self.initialize(X)[1],self.weights)
        lis = []
        for i in self.sigmoid(z):
            if i>0.5:
                lis.append(1)
            else:
                lis.append(0)
        return lis


In [76]:
obj1 = LogidticRegression()
model= obj1.fit(X_train,y_train)
y_pred = obj1.predict(X_test)
y_train1 = obj1.predict(X_train)
#Let's see the f1-score for training and testing data
f1_score_tr = F1_score(y_train,y_train1)
f1_score_te = F1_score(y_test,y_pred)


print(f1_score_tr)
print(f1_score_te)


0.40243902439024387
0.3687150837988827


In [77]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
cm = metrics.confusion_matrix(y_test,y_pred)
print(cm)

[[56816    45]
 [   68    33]]
